export const ncaaColumns = [
    { accessorKey: "Player", header: "Player" },
    { accessorKey: "Team", header: "Team" },
    { accessorKey: "Season", header: "Season" },
    { accessorKey: "Season Grade", header: "Season Grade" },
    { accessorKey: "WCr %", header: "WCr %" },
    { accessorKey: "WCr/GP", header: "WCr/GP" },
    { accessorKey: "MVPr", header: "MVPr" },
    { accessorKey: "MIN", header: "MIN" },
    { accessorKey: "PTS", header: "PTS" },
    { accessorKey: "FGM", header: "FGM" },
    { accessorKey: "FGA", header: "FGA" },
    { accessorKey: "3FM", header: "3FM" },
    { accessorKey: "3FA", header: "3FA" },
    { accessorKey: "2FM", header: "2FM" },
    { accessorKey: "2FA", header: "2FA" },
    { accessorKey: "FTM", header: "FTM" },
    { accessorKey: "FTA", header: "FTA" },
    { accessorKey: "OREB", header: "OREB" },
    { accessorKey: "DREB", header: "DREB" },
    { accessorKey: "REB", header: "REB" },
    { accessorKey: "AST", header: "AST" },
    { accessorKey: "STL", header: "STL" },
    { accessorKey: "BLK", header: "BLK" },
    { accessorKey: "TO", header: "TO" },
    { accessorKey: "PF", header: "PF" },
  ];
  
  export const nbaColumns = [
    { accessorKey: "Player", header: "Player" },
    { accessorKey: "Tm", header: "Team" },
    // { accessorKey: "Season", header: "Season" },
    { accessorKey: "Season Grade", header: "Season Grade" },
    { accessorKey: "WCr", header: "WCr" },
    { accessorKey: "WCr %", header: "WCr %" },
    { accessorKey: "WCr/GP", header: "WCr/GP" },
    { accessorKey: "MVPr", header: "MVPr" },
    { accessorKey: "MP", header: "MIN" },
    { accessorKey: "PTS", header: "PTS" },
    { accessorKey: "FG", header: "FG" },
    { accessorKey: "FGA", header: "FGA" },
    { accessorKey: "3P", header: "3P" },
    { accessorKey: "3PA", header: "3PA" },
    { accessorKey: "2P", header: "2P" },
    { accessorKey: "2PA", header: "2PA" },
    { accessorKey: "FT", header: "FT" },
    { accessorKey: "FTA", header: "FTA" },
    { accessorKey: "ORB", header: "ORB" },
    { accessorKey: "DRB", header: "DRB" },
    { accessorKey: "REB", header: "REB" },
    { accessorKey: "AST", header: "AST" },
    { accessorKey: "STL", header: "STL" },
    { accessorKey: "BLK", header: "BLK" },
    { accessorKey: "TOV", header: "TO" },
    { accessorKey: "PF", header: "PF" },
  ];